version = 3.11.3

runner.dialect = scala3
maxColumn = 120
newlines.topLevelStatementBlankLines = [
  { blanks: { after: 0 } }
]

rewrite {
  rules = [Imports, AvoidInfix, RedundantParens, RemoveSemicolons]
  scala3.convertToNewSyntax = true
  scala3.newSyntax.control = false
  scala3.newSyntax.deprecated = true

  imports {
    groups = [["javax?\\..*"], ["scala\\..*"], [".*"], ["com\\.kevel\\..*"]]
    sort = ascii
    selectors = fold
  }
}
