addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"    % "0.13.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp"         % "2.3.1")
addSbtPlugin("com.github.sbt" % "sbt-release"     % "1.4.0")
addSbtPlugin("com.github.sbt" % "sbt-boilerplate" % "0.7.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"        % "2.6.2")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"    % "3.12.2")
